
from __future__ import print_function
# This file was *autogenerated* from the file small_exponent.sage
from sage.all_cmdline import *   # import sage library

_sage_const_7 = Integer(7); _sage_const_0p8 = RealNumber('0.8'); _sage_const_3 = Integer(3); _sage_const_0 = Integer(0); _sage_const_1 = Integer(1); _sage_const_60 = Integer(60); _sage_const_2 = Integer(2); _sage_const_4 = Integer(4); _sage_const_512 = Integer(512); _sage_const_511 = Integer(511); _sage_const_0p292 = RealNumber('0.292'); _sage_const_0xf4c548636db62ffcc7ac4a0797952bea9a65bd426175af2435f72657e67ec8194667bfa94ce23c6f1e5baf3201867ab41701f6b8768e71009c41a3d5e9e7c109455341d549c7611f9f52851a2f017906aa9ccbedb95d238468e2c8577d30ecc4f158e3811fd5e2a6051443d468e3506bbc39bba710e34a604ac9e85d0feef8b3 = Integer(0xf4c548636db62ffcc7ac4a0797952bea9a65bd426175af2435f72657e67ec8194667bfa94ce23c6f1e5baf3201867ab41701f6b8768e71009c41a3d5e9e7c109455341d549c7611f9f52851a2f017906aa9ccbedb95d238468e2c8577d30ecc4f158e3811fd5e2a6051443d468e3506bbc39bba710e34a604ac9e85d0feef8b3); _sage_const_0x16f4b438ba14e05afa944f7da9904f8c78ea52e4ca0be7fa2b5f84e22ddd7b0578a3477b19b7bb4a7f825acc45da2dd10e62dbd94a3386b97d92ee817b0c66c1507514a7860b9139bc2ac3a4e0fe304199214da00a4ca82bfcb7b18253e7e6144828e584dac2dfb9a03fabaf2376ce7c269923fbb60fc68325b9f6443e1f896f = Integer(0x16f4b438ba14e05afa944f7da9904f8c78ea52e4ca0be7fa2b5f84e22ddd7b0578a3477b19b7bb4a7f825acc45da2dd10e62dbd94a3386b97d92ee817b0c66c1507514a7860b9139bc2ac3a4e0fe304199214da00a4ca82bfcb7b18253e7e6144828e584dac2dfb9a03fabaf2376ce7c269923fbb60fc68325b9f6443e1f896f); _sage_const_10 = Integer(10); _sage_const_30 = Integer(30); _sage_const_0p293 = RealNumber('0.293'); _sage_const_300 = Integer(300)
import logging
import time
import os
from datetime import datetime
from fpylll import IntegerMatrix, LLL
from sage.parallel.decorate import parallel
from sage.rings.polynomial.polynomial_ring_constructor import PolynomialRing
from sage.all import QQ
from sage.all import RR
from sage.all import ZZ
from sage.all import Zmod
from sage.all import is_prime, power_mod, round, sqrt
from sage.all import parallel
from sage.rings.integer import Integer
import multiprocessing



debug = False
strict = False
helpful_only = True
dimension_min = _sage_const_7  # stop removing if lattice reaches that dimension

def Factor_by_d(d, e, N):
    k = round((e * d)/N)
    s = (e * d - 1)/k - N - 1
    s = -s
    p = s/2 + sqrt(s**2/4-N)
    q = N / p
    return p,q

def reduce_lattice(B, delta=_sage_const_0p8 ):
    verbose = False
    # Reduce basis
    start = time.time()  # Can't use cputime here, because it does not catch os.system(...).  
    logging.debug(f"Reducing a {B.nrows()} x {B.ncols()} lattice...")

    # Generate a timestamp for unique filenames
    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S_%f")[:-_sage_const_3 ]  # Remove the last three digits to get milliseconds
    basis_filename = f"basis_{timestamp}.tmp"
    output_filename = f"basis_out_{timestamp}.tmp"

    with open(basis_filename, "w+") as f:
        # Would prefer to simply use IntegerMatrix here, but IntegerMatrix.__str()__ results in crash.
        B_str = B.str()
        B_str = '\n'.join(' '.join(line.split()) for line in B_str.split('\n'))
        f.write("[\n" + B_str + "\n]")

    # Execute the external command
    success = os.system(f"flatter -v {basis_filename} {output_filename} >/dev/null 2>&1")

    os.remove(basis_filename)

    if success == _sage_const_0 :
        B_LLL = matrix(IntegerMatrix.from_file(output_filename))
        os.remove(output_filename)
    else:
        if verbose:
            print("flatter not found. Resorting to FPLLL.")
        B_LLL = B.LLL(delta)

    stop = time.time()
    if verbose:
        print("Finished basis Flatter reduction. Time: %fs." % (stop - start))
    return B_LLL

# display stats on helpful vectors
def helpful_vectors(BB, modulus):
    nothelpful = _sage_const_0 
    for ii in range(BB.dimensions()[_sage_const_0 ]):
        if BB[ii,ii] >= modulus:
            nothelpful += _sage_const_1 
    if(debug):
        print(nothelpful, "/", BB.dimensions()[_sage_const_0 ], " vectors are not helpful")
 
# display matrix picture with 0 and X
def matrix_overview(BB, bound):
    for ii in range(BB.dimensions()[_sage_const_0 ]):
        a = ('%02d ' % ii)
        for jj in range(BB.dimensions()[_sage_const_1 ]):
            a += '0' if BB[ii,jj] == _sage_const_0  else 'X'
            if BB.dimensions()[_sage_const_0 ] < _sage_const_60 :
                a += ' '
        if BB[ii, ii] >= bound:
            a += '~'
        print(a)
 
# tries to remove unhelpful vectors
# we start at current = n-1 (last vector)
def remove_unhelpful(BB, monomials, bound, current):
    # end of our recursive function
    if current == -_sage_const_1  or BB.dimensions()[_sage_const_0 ] <= dimension_min:
        return BB
 
    # we start by checking from the end
    for ii in range(current, -_sage_const_1 , -_sage_const_1 ):
        # if it is unhelpful:
        if BB[ii, ii] >= bound:
            affected_vectors = _sage_const_0 
            affected_vector_index = _sage_const_0 
            # let's check if it affects other vectors
            for jj in range(ii + _sage_const_1 , BB.dimensions()[_sage_const_0 ]):
                # if another vector is affected:
                # we increase the count
                if BB[jj, ii] != _sage_const_0 :
                    affected_vectors += _sage_const_1 
                    affected_vector_index = jj
 
            # level:0
            # if no other vectors end up affected
            # we remove it
            if affected_vectors == _sage_const_0 :
                if(debug):
                    print("* removing unhelpful vector", ii)
                BB = BB.delete_columns([ii])
                BB = BB.delete_rows([ii])
                monomials.pop(ii)
                BB = remove_unhelpful(BB, monomials, bound, ii-_sage_const_1 )
                return BB
 
            # level:1
            # if just one was affected we check
            # if it is affecting someone else
            elif affected_vectors == _sage_const_1 :
                affected_deeper = True
                for kk in range(affected_vector_index + _sage_const_1 , BB.dimensions()[_sage_const_0 ]):
                    # if it is affecting even one vector
                    # we give up on this one
                    if BB[kk, affected_vector_index] != _sage_const_0 :
                        affected_deeper = False
                # remove both it if no other vector was affected and
                # this helpful vector is not helpful enough
                # compared to our unhelpful one
                if affected_deeper and abs(bound - BB[affected_vector_index, affected_vector_index]) < abs(bound - BB[ii, ii]):
                    if(debug):
                        print("* removing unhelpful vectors", ii, "and", affected_vector_index)
                    BB = BB.delete_columns([affected_vector_index, ii])
                    BB = BB.delete_rows([affected_vector_index, ii])
                    monomials.pop(affected_vector_index)
                    monomials.pop(ii)
                    BB = remove_unhelpful(BB, monomials, bound, ii-_sage_const_1 )
                    return BB
    # nothing happened
    return BB
 
def boneh_durfee(pol, modulus, mm, tt, XX, YY):
    # substitution (Herrman and May)
    PR = PolynomialRing(ZZ, names=('u', 'x', 'y',)); (u, x, y,) = PR._first_ngens(3)
    Q = PR.quotient(x*y + _sage_const_1  - u) # u = xy + 1
    polZ = Q(pol).lift()
 
    UU = XX*YY + _sage_const_1 
 
    # x-shifts
    gg = []
    for kk in range(mm + _sage_const_1 ):
        for ii in range(mm - kk + _sage_const_1 ):
            xshift = x**ii * modulus**(mm - kk) * polZ(u, x, y)**kk
            gg.append(xshift)
    gg.sort()
 
    # x-shifts list of monomials
    monomials = []
    for polynomial in gg:
        for monomial in polynomial.monomials():
            if monomial not in monomials:
                monomials.append(monomial)
    monomials.sort()
    
    # y-shifts (selected by Herrman and May)
    for jj in range(_sage_const_1 , tt + _sage_const_1 ):
        for kk in range(floor(mm/tt) * jj, mm + _sage_const_1 ):
            yshift = y**jj * polZ(u, x, y)**kk * modulus**(mm - kk)
            yshift = Q(yshift).lift()
            gg.append(yshift) # substitution
    
    # y-shifts list of monomials
    for jj in range(_sage_const_1 , tt + _sage_const_1 ):
        for kk in range(floor(mm/tt) * jj, mm + _sage_const_1 ):
            monomials.append(u**kk * y**jj)
 
    # construct lattice B
    nn = len(monomials)
    BB = Matrix(ZZ, nn)
    for ii in range(nn):
        BB[ii, _sage_const_0 ] = gg[ii](_sage_const_0 , _sage_const_0 , _sage_const_0 )
        for jj in range(_sage_const_1 , ii + _sage_const_1 ):
            if monomials[jj] in gg[ii].monomials():
                BB[ii, jj] = gg[ii].monomial_coefficient(monomials[jj]) * monomials[jj](UU,XX,YY)
 
    # Prototype to reduce the lattice
    if helpful_only:
        # automatically remove
        BB = remove_unhelpful(BB, monomials, modulus**mm, nn-_sage_const_1 )
        # reset dimension
        nn = BB.dimensions()[_sage_const_0 ]
        if nn == _sage_const_0 :
            print("failure")
            return _sage_const_0 ,_sage_const_0 
 
    # check if vectors are helpful
    if debug:
        helpful_vectors(BB, modulus**mm)
    
    # check if determinant is correctly bounded
    det = BB.det()
    bound = modulus**(mm*nn)
    if det >= bound:
        print("We do not have det < bound. Solutions might not be found.")
        print("Try with highers m and t.")
        if debug:
            diff = (log(det) - log(bound)) / log(_sage_const_2 )
            print("size det(L) - size e**(m*n) = ", floor(diff))
        if strict:
            return -_sage_const_1 , -_sage_const_1 
    else:
        print("det(L) < e**(m*n) (good! If a solution exists < N**delta, it will be found)")
 
    # display the lattice basis
    if debug:
        matrix_overview(BB, modulus**mm)
 
    # LLL
    if debug:
        print("optimizing basis of the lattice via LLL, this can take a long time")
    
    print("BB dimension:", BB.dimensions())
    start_time = time.time()
    BB = BB.LLL()
    end_time = time.time()
    print("reduction time:", end_time - start_time)
    # BB = reduce_lattice(BB, delta=0.8)
   # BB = BB.BKZ(block_size = 25)
    if debug:
        print("LLL is done!")
 
    # transform vector i & j -> polynomials 1 & 2
    if debug:
        print("looking for independent vectors in the lattice")
    found_polynomials = False
    start_time = time.time()
    for pol1_idx in range(nn - _sage_const_1 ):
        for pol2_idx in range(pol1_idx + _sage_const_1 , nn):
            # for i and j, create the two polynomials
            PR = PolynomialRing(ZZ, names=('w', 'z',)); (w, z,) = PR._first_ngens(2)
            pol1 = pol2 = _sage_const_0 
            for jj in range(nn):
                pol1 += monomials[jj](w*z+_sage_const_1 ,w,z) * BB[pol1_idx, jj] / monomials[jj](UU,XX,YY)
                pol2 += monomials[jj](w*z+_sage_const_1 ,w,z) * BB[pol2_idx, jj] / monomials[jj](UU,XX,YY)
 
            # resultant
            PR = PolynomialRing(ZZ, names=('q',)); (q,) = PR._first_ngens(1)
            rr = pol1.resultant(pol2)

            # are these good polynomials?
            if rr.is_zero() or rr.monomials() == [_sage_const_1 ]:
                continue
            else:
                print("found them, using vectors", pol1_idx, "and", pol2_idx)
                found_polynomials = True
                break
        if found_polynomials:
            break
 
    if not found_polynomials:
        print("no independant vectors could be found. This should very rarely happen...")
        return _sage_const_0 , _sage_const_0 
    
    rr = rr(q, q)
    # solutions
    soly = rr.roots()
 
    if len(soly) == _sage_const_0 :
        print("Your prediction (delta) is too small")
        return _sage_const_0 , _sage_const_0 
 
    soly = soly[_sage_const_0 ][_sage_const_0 ]
    ss = pol1(q, soly)
    solx = ss.roots()[_sage_const_0 ][_sage_const_0 ]
    end_time = time.time()
    print("solution time:", end_time - start_time)
    return solx, soly

@parallel(p_iter='fork', ncpus=_sage_const_4 ) 
def boneh_durfee_iterator(N, e, delta, m, t, s, X, Y, msb):
    
    ############################################
    # How To Use This Script
    ##########################################

    #
    # The problem to solve (edit the following values)
    #
 
    # the hypothesis on the private exponent (the theoretical maximum is 0.292)

    # delta = 0.293
    # m = 7
    # s = 30 # number of msb enumerated
    # t = ceil((1-2*delta) * m)
    if debug:
        print("msb:",msb)
    pmsb = msb
    #print("pmsb is ", pmsb)
    qmsb = N/(pmsb * _sage_const_2 **(_sage_const_512  - s) + _sage_const_2 **(_sage_const_511  - s - _sage_const_1) )
    qmsb = floor(qmsb / _sage_const_2 **(_sage_const_512  - s))

    # X = 2^300  # this _might_ be too much
    # #Y = floor(N^(1/2))    # correct if p, q are ~ same size
    # Y = floor(2*floor(N^(1/2)/2^s))
    # #Y = 2^300
    #
    # Don't touch anything below
    #

    # Problem put in equation
    P = PolynomialRing(ZZ, names=('x', 'y',)); (x, y,) = P._first_ngens(2)
    #A = int((N+1)/2)
    A = N + _sage_const_1 -pmsb*_sage_const_2 **(_sage_const_512  - s)-qmsb*_sage_const_2 **(_sage_const_512  - s)
    pol = _sage_const_1  + x * (A + y)

    #
    # Find the solutions!
    #

    # Checking bounds
    if debug:
        print("=== checking values ===")
        print("* delta:", delta)
        print("* delta < 0.292", delta < _sage_const_0p292 )
        print("* size of e:", int(log(e)/log(_sage_const_2 )))
        print("* size of N:", int(log(N)/log(_sage_const_2 )))
        print("* m:", m, ", t:", t)

    # boneh_durfee
    if debug:
        print("=== running algorithm ===")
        start_time = time.time()

    solx, soly = boneh_durfee(pol, e, m, t, X, Y)
    d0 = int(pol(solx, soly) / e)
    if solx > _sage_const_0 :
        return d0
    return _sage_const_0

def BonehDurfee_LZQ23(N, e, delta, m, t, s, g, parallel_num):
    # res = example(2^29)
    # print(res)
    # res = example([])

    start_time = time.time()
    flag = False
    #cnt = 0
    # X = floor(N **( delta +  _sage_const_1))
    X = floor(N ** (delta))   
    # X = 2 ** 300 # this _might_ be too much
    Y = floor(_sage_const_2 *floor(N**(_sage_const_1 /_sage_const_2 )/_sage_const_2 **s))

    for i in range(_sage_const_0 , _sage_const_2 **g):
        if debug:
            print("i is ", i)
        if flag == True:
            break
        idx = _sage_const_0 
        while idx < _sage_const_2 **(s-g-_sage_const_1 ):
            if debug:
                print("idx is ", idx)
            if flag == True:
                break
            res = boneh_durfee_iterator([(N, e, delta, m, t, s, X, Y, (_sage_const_2 **(s-_sage_const_1 ) + tt * (_sage_const_2 **g) + i)) 
                                            for tt in range(idx, idx + parallel_num)]) #First bit is 1, so beginning at 2^(s-1)
            # print("coming here")
            # print(res)
            idx = idx + parallel_num
            for xx in res:
                # print(xx[1])
                if xx[_sage_const_1 ]!= _sage_const_0 :
                    # print(xx)
                    flag = True
                    d = xx[_sage_const_1 ]
                    print("private key found:", d)
                    p_, q_ = Factor_by_d(d, e, N)
                    return(p_, q_, d)
                    break
                #print(xx[1])
            print(time.time() - start_time, " seconds")

